spring.application.name=Monitoring

server.port=8080

# PostgreSQL Connection (Change the username/password if yours are different!)
spring.datasource.url=jdbc:postgresql://localhost:5432/monitoring_db
spring.datasource.username=postgres
spring.datasource.password=root


# Tell Spring to automatically create and update our database tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true